---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
    # CRD is installed from the helm chart
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selfSigned: {}

